### ISSUE TITLE
Last Traded Price in addition to Closing Price

### ISSUE THREAD

**Issue by FinAstro** [pparesh25/Getbhavcopy-alternative#14]
Hi .. Is it possible to extract LTP (Last Traded Price) in addition to close price?

**Comment by pparesh25** [comment]
yes

**Comment by pparesh25** [comment]
open  >>> New-Getbhavcopy-Eq-with original Indexes name .py <<<  file with some good text editor,
 in file line 77 remove >>> 'LastPric',  <<< this entry,
 it will remains LastPrice column in bhavcopy text file.
 but you need to remove close price column by adding this >>> 'ClsPric' <<< entry to that list,
 otherwise import to amibriker gives you error, and you modify import format it's also not work because of indexes data

**Comment by pparesh25** [comment]
I think you don't know what is the importance of closing price, closing price is the most important price point on particular day. And to set average price of last few minute as a closing price is due to high volatility in last few minute.
